### 공통 변수 설정
@baseUrl = http://localhost:8001
@fileName = test.jpg
@videoFileName = test.mp4
@contentType = image/jpeg
@videoContentType = video/mp4
@fileSize = 12345

### 1. 업로드용 Presigned URL 발급 (이미지)
POST {{baseUrl}}/api/s3/presigned-url
Content-Type: application/json

{
  "fileName": "{{fileName}}",
  "fileType": "Image",
  "size": {{fileSize}},
  "contentType": "{{contentType}}"
}

### 2. 업로드용 Presigned URL 발급 (비디오)
POST {{baseUrl}}/api/s3/presigned-url
Content-Type: application/json

{
  "fileName": "{{videoFileName}}",
  "fileType": "Video",
  "size": {{fileSize}},
  "contentType": "{{videoContentType}}"
}

### 3. 업로드 완료 확인
# 주의: 아래 fileName은 위 API 응답에서 얻은 실제 생성된 파일명으로 변경해야 합니다
POST {{baseUrl}}/api/s3/confirm-upload
Content-Type: application/json

{
  "fileName": "generated-uuid-file-name.jpg",
  "originalFileName": "{{fileName}}",
  "fileType": "Image",
  "size": {{fileSize}}
}

### 4. 기존 파일에 대한 Presigned URL 발급
# 주의: 아래 fileName은 실제 존재하는 파일명으로 변경해야 합니다
GET {{baseUrl}}/api/s3/presigned-url/generated-uuid-file-name.jpg

### 5. 단일 파일 조회
# 주의: 아래 fileName은 실제 존재하는 파일명으로 변경해야 합니다
GET {{baseUrl}}/api/s3/file/generated-uuid-file-name.jpg

### 6. 파일 URL 조회
# 주의: 아래 fileName은 실제 존재하는 파일명으로 변경해야 합니다
GET {{baseUrl}}/api/s3/files/image/generated-uuid-file-name.jpg

### 7. 모든 파일 목록 조회
GET {{baseUrl}}/api/s3/files

### 8. 이미지 파일 목록 조회
GET {{baseUrl}}/api/s3/files/image

### 9. 비디오 파일 목록 조회
GET {{baseUrl}}/api/s3/files/video

### 10. 파일 삭제
# 주의: 아래 fileName은 실제 존재하는 파일명으로 변경해야 합니다
DELETE {{baseUrl}}/api/s3/files/image/generated-uuid-file-name.jpg 