stages:
  - deploy-jenkins-trigger

deploy-jenkins-trigger:
  stage: deploy-jenkins-trigger
  image: badouralix/curl-jq
  tags:
    - "ci / cd"

  variables:
    JOB_NAME: "deploy-build-test"
    JENKINS_MAIN_URL: "${JENKINS_MAIN_URL%/}"
    TRIGGER_URL: "$JENKINS_MAIN_URL/job/$JOB_NAME/buildWithParameters"
    TOKEN: "$JENKINS_KEY_NAME"
    PARAM_BRANCH: "$CI_COMMIT_REF_NAME"

  script: |
    set -euo pipefail
    
    # 인증 정보 제거한 repo URL 생성
    PARAM_REPO_CLEAN=$(echo "$CI_REPOSITORY_URL" | sed -E 's#https://[^@]+@#https://#')
    
    # Jenkins 잡 트리거
    RESPONSE_HEADERS=$(curl -siS -X POST "$TRIGGER_URL" \
      --user "$JENKINS_USER:$JENKINS_KEY_VALUE" \
      --data-urlencode "token=$TOKEN" \
      --data-urlencode "BRANCH_NAME=$PARAM_BRANCH" \
      --data-urlencode "GIT_REPO_URL=$PARAM_REPO_CLEAN")
    
    # Location 헤더에서 queue path 추출 (HTTPS 지원)
    QUEUE_PATH=$(echo "$RESPONSE_HEADERS" \
      | grep -i '^Location:' \
      | awk '{print $2}' \
      | sed -E 's#https?://[^/]+(/jenkins)?(/queue/item/[0-9]+/)#\2#' \
      | tr -d '\r')
    
    # queue path가 슬래시로 시작하는지 확인하고 API URL 구성
    if [[ "$QUEUE_PATH" == */ ]]; then
      QUEUE_API_URL="$JENKINS_MAIN_URL$QUEUE_PATH"api/json
    else
      QUEUE_API_URL="$JENKINS_MAIN_URL$QUEUE_PATH/api/json"
    fi
    
    # 빌드 번호 대기
    BUILD_NUMBER=""
    for i in $(seq 1 30); do
      INFO=$(curl -sS \
        --user "$JENKINS_USER:$JENKINS_KEY_VALUE" \
        "$QUEUE_API_URL" || echo '{}')
      
      # JSON 유효성 검사
      if ! echo "$INFO" | jq empty 2>/dev/null; then
        echo "❌ Jenkins 응답이 JSON 형식이 아님"
        exit 1
      fi
      
      BUILD_NUMBER=$(echo "$INFO" | jq -r '.executable.number // empty')
      if [ -n "$BUILD_NUMBER" ]; then
        echo "✅ 빌드 번호: $BUILD_NUMBER"
        break
      fi
      echo "⏳ 큐 대기 중 ($i)…"
      sleep 2
    done
    
    if [ -z "$BUILD_NUMBER" ]; then
      echo "❌ 빌드 번호를 가져오지 못했습니다"
      exit 1
    fi

    # 빌드 상태 추적
    JOB_API="$JENKINS_MAIN_URL/job/$JOB_NAME/$BUILD_NUMBER/api/json"
    elapsed=0
    while [ $elapsed -lt 300 ]; do
      RESULT=$(curl -sS \
        --user "$JENKINS_USER:$JENKINS_KEY_VALUE" \
        "$JOB_API" \
        | jq -r '.result // "BUILDING"')
      if [ "$RESULT" != "BUILDING" ]; then
        if [ "$RESULT" = "SUCCESS" ]; then
          echo "✅ Jenkins build #$BUILD_NUMBER SUCCESS"
          exit 0
        else
          echo "❌ Jenkins build #$BUILD_NUMBER FAILED: $RESULT"
          exit 1
        fi
      fi
      echo "⏳ 빌드 진행 중… (${elapsed}s)"
      sleep 10
      elapsed=$((elapsed + 10))
    done

    echo "❌ Jenkins 빌드 대기 시간 초과"
    exit 1 