stages:
  - deploy-ai-server

deploy-ai-server:
  stage: deploy-ai-server
  image: jonz94/rsync-ssh-alpine:3.1.3-6
  tags:
    - "ci / cd"

  before_script:
    - mkdir -p ~/.ssh
    # SSH 개인 키를 base64로 인코딩된 환경 변수에서 디코딩하여 저장
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

  script:
    # .venv 디렉토리를 제외한 모든 파일 삭제
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "find /home/ubuntu/ai-server/ai -mindepth 1 -not -path '*/\.venv*' -delete"
    
    # 로컬 ai 디렉토리의 모든 파일을 .venv를 제외하고 전송
    - rsync -avz --exclude='.venv' -e "ssh -o StrictHostKeyChecking=no" ./ai/ "$DEPLOY_USER@$DEPLOY_HOST:/home/ubuntu/ai-server/ai/"
    
    # 가상환경 활성화 및 의존성 설치
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "cd /home/ubuntu/ai-server/ai && source .venv/bin/activate && uv pip install -e ."
    
    # AI 서버 재시작
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "sudo systemctl restart ai-server"
    
    - echo "✅ AI 서버 배포 완료"
