stages:
  - transfer-model

transfer-model:
  stage: transfer-model
  image: jonz94/rsync-ssh-alpine:3.1.3-6
  tags:
    - "ci / cd"

  before_script:
    - mkdir -p ~/.ssh
    # SSH 개인 키를 base64로 인코딩된 환경 변수에서 디코딩하여 저장
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

  script:
    # SSH 연결 설정 및 디렉토리 생성
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "mkdir -p /home/ubuntu/ai-server/ai/src/app/resources/"
    
    # 완전한 동기화 (로컬에 없는 파일은 원격에서도 삭제)
    - rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ai/src/app/resources/ "$DEPLOY_USER@$DEPLOY_HOST:/home/ubuntu/ai-server/ai/src/app/resources/"
    
    # 백업 생성 (날짜와 시간을 포함한 디렉토리에 저장)
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "mkdir -p /home/ubuntu/ai-server/backups/resources-\$(date +%Y%m%d-%H%M%S) && cp -r /home/ubuntu/ai-server/ai/src/app/resources/* /home/ubuntu/ai-server/backups/resources-\$(date +%Y%m%d-%H%M%S)/"
    
    - echo "✅ 모델 파일 전송 및 동기화 완료"
